### ISSUE TITLE
move pipelines directory from hera_pspec to hera_stats

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_stats#10]
Even though it contains the "power spectrum pipeline", the `pipelines` directory probably belongs in `hera_stats` b/c `hera_stats` is "top-of-the-food-chain" in terms of code dependency. i.e., we can't import `hera_stats` in `hera_pspec` and use some of the stuff that should go at the very end of the power spectrum pipeline. b/c of this, we should just move all the pipeline scripts to `hera_stats`, and also put in unit tests

**Comment by philbull** [comment]
We discussed this yesterday (Nick, Adrian, and me) and decided against this.
