### ISSUE TITLE
is complex multiplication correct for stats.weightedsum?

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_stats#13]
In `stats.weightedsum` we are doing things like multiplying complex spectra with complex errors in doing a weighted sum. Do we mean to perform complex multiplication and therefore tie together real and imaginary components of the two arrays? Or, should we be separately averaging the real and imaginary components of these arrays?

**Comment by duncanjmr** [comment]
The data type of jkset is not complex. When jkset is given a PSpecContainer or uvp_list, it projects it into the real (this being as of right now, I want to change this and make imaginary accessable). When fed through weightedsum, the data is already real.

We could also keep everything in jkset complex and do it the way you are talking about, and add jkset.imag() or jkset.real() as additional functions to specify. In this case, weightedsum would do the real and imaginary components separately and then recombine them to produce a complex averaged jkset.

The latter might be the smarter/better way of doing it and preserving all the data.

**Comment by philbull** [comment]
Closing this issue as `weightedsum` has been deprecated.
