### ISSUE TITLE
`stripe_times` has a confusing way of handling None period.

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_stats#15]
Lines 296-299 could be simplified to find the set of periods in a more straightforward manner. Lily's going to take a look at this (not yet in HERA-Team, so I can't assign her).

https://github.com/HERA-Team/hera_stats/blob/53b76fbf0fdb56535c6ed60aed9d5d4f8b4a14aa/hera_stats/jackknives.py#L299

**Comment by philbull** [comment]
This function has now been deprecated.
